service: bookgpt-backend

frameworkVersion: "2"

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-2

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-ruby-layer
