service: bookgpt-backend

frameworkVersion: "2"

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-2

functions:
  ask:
    handler: app/handler.ask
    environment: ${file(env.json)}
    timeout: 30
    package:
      patterns:
        - embeddings/*.csv
    events:
      - http:
          path: /ask
          method: POST
          cors: true

plugins:
  - serverless-ruby-layer
